# Generated by Django 5.0.6 on 2024-06-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.supplier')),
            ],
            options={
                'unique_together': {('item', 'supplier')},
            },
        ),
    ]
