# Generated by Django 5.0.6 on 2024-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_itemsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='items_info',
            field=models.ManyToManyField(related_name='suppliers_info', to='online_store.item'),
        ),
        migrations.DeleteModel(
            name='ItemSupplier',
        ),
    ]
